-- require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autopairs")
require("user.alpha")
require("user.bufferline")
require("user.comment")
require("user.gitsigns")
require("user.illuminate")
require("user.indentline")
require("user.lualine")
require("user.nvim-tree")
require("user.nvim-webdev-icons")
require("user.project")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.colorscheme")
-- require("user.base")
require("user.cmp")
require("user.autocommands")
require("user.whichkey")
require("user.harpoon")
require("user.neo-scroll")
require("user.lsp")
require("user.ts-autotag")
-- require("user.nvim-colorizer")
require("user.dap")
require("user.copilot")
-- add a file named copilot
